ci: Added attemps for jenkins triggers

diff --git a/.github/workflows/build_docker_img.yml b/.github/workflows/build_docker_img.yml
--- a/.github/workflows/build_docker_img.yml
+++ b/.github/workflows/build_docker_img.yml
@@ -72,7 +72,18 @@ jobs:
       - name: Trigger Jenkins deploy (staging)
         if: success()
         run: |
-          curl -sS -X POST \
-            "https://jenkins-superlista.duckdns.org/generic-webhook-trigger/invoke?token=superlista-staging" \
-            -H "Content-Type: application/json" \
-            -d '{"source":"github-actions","repo":"${{ github.repository }}","tag":"${{ steps.calculate_tag.outputs.NEW_TAG }}","lts":"true"}'
+          for i in {1..3}; do
+            echo "Attempt $i to trigger Jenkins deploy..."
+            curl -sS -X POST \
+              "https://jenkins-superlista.duckdns.org/generic-webhook-trigger/invoke?token=superlista-staging" \
+              -H "Content-Type: application/json" \
+              -d '{"source":"github-actions","repo":"${{ github.repository }}","tag":"${{ steps.calculate_tag.outputs.NEW_TAG }}","lts":"true"}' && break || {
+              if [ $i -lt 3 ]; then
+                echo "Failed to trigger Jenkins, retrying in 10 seconds..."
+                sleep 10
+              else
+                echo "Failed after $i attempts."
+                exit 1
+              fi
+            }
+          done
